---
name: CI ROS 2 images

on:
  pull_request:
    paths:
    - '.ci/**'
    - '.github/workflows/ros2_ci.yaml'
    - 'ros2/nightly/**'
    - 'ros2/source/**'
    - 'ros2/testing/**'
  push:
    branches-ignore:
    - 'master'
    paths:
    - '.ci/**'
    - '.github/workflows/ros2_ci.yaml'
    - 'ros2/nightly/**'
    - 'ros2/source/**'
    - 'ros2/testing/**'
jobs:
  build_images:
    strategy:
      fail-fast: false
      matrix:
        env:
          - {HUB_REPO: ros2, HUB_RELEASE: testing}
          - {HUB_REPO: ros2, HUB_RELEASE: source}
          - {HUB_REPO: ros2, HUB_RELEASE: nightly}
        platform:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v5
      - name: Check and build ROS 2 image
        env: ${{matrix.env}}
        run: |
          cd $HUB_REPO/$HUB_RELEASE
          make build
